### ISSUE TITLE
Collaborator Summit 2022 - Dublin, Ireland (NodeConf EU)

### ISSUE THREAD

**Issue by darcyclarke** [openjs-foundation/summit#323] opened 2022-05-09 18:38 UTC
## Collaborator Summit 2022

**Date:** Oct 1-2, 2022
**Venue:** [Landings WeWork, Dublin, Ireland](https://g.page/WeWork-2-Dublin-Landings?share)
**Cost:** Free
**Schedule:** [Google Sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing)
**Registration:** [Register here](https://www.eventbrite.com/e/openjs-foundation-collaborator-summit-dublin-tickets-410575531467). Everyone must register.
**Session Proposal:** Please submit your session by opening a [new issue](https://github.com/openjs-foundation/summit/issues/new?assignees=waleedashraf%2C+mcollina&labels=Dublin+2022%2C+Collaborator+Summit%2C+Session+Proposal&template=summit-topic-proposal.md&title=Session+Proposal%3A+%3CProject+Name%3E+%3CSession+Title%3E)

OpenJS Foundation Slack: https://slack-invite.openjsf.org/
#collabsummit channel: https://openjs-foundation.slack.com/archives/CPE10404W

## See also
- [Collab Summit Welcome Guide](https://github.com/openjs-foundation/summit/tree/main/2022-10-01-Dublin)
- [Session Facilitator Guide](https://github.com/openjs-foundation/summit/blob/main/SESSION_FACILITATOR_GUIDE.md#-session-facilitator-guide)

## Local Transportation
Dublin -> Killkenny train is ~€9 prebooked or ~€16 on the platform.
https://www.irishrail.ie/en-ie/Offer/webfares

Lyrath is a 7 min taxi at the other end.

Ireland typically uses FreeNow rather than Uber.
https://www.free-now.com/ie/

## Nodeconf.eu
**Date:** Oct 3-5, 2022
**Venue:** [The Lyrath Estate, Kilkenny, Ireland](https://goo.gl/maps/NezS89tBqdvKzfT46)
**Registration:** https://nodeconf.eu/

**Comment by Trott** [comment] 2022-05-09 18:56
@rginn @brianwarner @jorydotcom

**Comment by WaleedAshraf** [comment] 2022-05-09 21:15
I'll bring this up in our coming Program Committee meeting.

**Comment by WaleedAshraf** [comment] 2022-05-16 21:49
We discussed this in the last meeting. There were 2 concerns/questions raised.
1. Putting it together with NodeConf might sound like it's Node.js Collab Summit?
2. Would it be possible for collaborators to attend if it happens the weekend before NodeConf, in **Dublin**. OpenJSF can get space more easily in Dublin because of the offices of sponsor companies.

WDYT?

Personally, for the 1st point, I think we'll have to host it together with some conf/event. So, the one which makes sense is Node.js, because of its biggest community VS other projects.
For 2nd point, I think that's also fine. Dublin is only 2hrs (on the train) away from Kilkenny.

**Comment by mcollina** [comment] 2022-05-17 06:51
The quote for the meetings rooms for 50 people at the NodeConf venue is around 2500 euros, including refreshments and lunch for 50 attendees.
If you want to do it in Dublin instead, I highly recommend before the conference.

**Comment by ruyadorno** [comment] 2022-05-19 13:55
maybe compare costs (not only for the venue but also compare cost of accommodation for folks coming from outside the country) between before-NodeConf.eu in Dublin/Kilkenny and after-Nordic.js in Stockholm

**Comment by rginn** [comment] 2022-05-23 21:49
These are all great options! I've reached out to the Nordic.js organizers to learn more. We'll also reach out to our other OpenJS projects internally to gauge their interest in a fall Collab Summit in Europe and time/location preferences.

**Comment by targos** [comment] 2022-05-24 04:20
I hope it won't take too much time to make a decision. I have a ticket for NodeConf EU and need to book flights and accommodation.

**Comment by eemeli** [comment] 2022-05-24 05:27
As additional data points to add here, NodeConf EU is currently selling "Early Bird" tickets at €750, while Nordic.js is selling "Late Bird" tickets at about €895. Without further insider info, this to me suggests that starting to plan now for a companion event might be easier with NodeConf compared to Nordic.js.

And just to throw one more possibility into the mix, I'm involved in organising [React Finland](https://react-finland.fi/) here in Helsinki 12-16 September. Despite its name, in content it is a general front-end conference, and we'd be happy to help organise a collab summit in association with it. We are currently selling "Early Bird" tickets at €399.

**Comment by mcollina** [comment] 2022-06-11 15:34
After chatting with @rginn, @mhdawson and @jasnell, we will be looking into verifying the viability of a Collab Summit on the **1st and 2nd of October in Dublin**.

**Comment by mcollina** [comment] 2022-06-29 17:35
Have you got any updates? We should finalize a date and announce it.

**Comment by mcollina** [comment] 2022-06-29 19:38
@no9 could you confirm if IBM/RedHat could host us?

**Comment by WaleedAshraf** [comment] 2022-06-29 21:07
@rginn You can add me. @mcollina also mentioned the same.

**Comment by mhdawson** [comment] 2022-06-29 21:08
@mcollina I had an initial discussion with @No9 and one of the leaders from the RH office. Still working through some details to see if/what is possible and we should be getting back together next week.

**Comment by mhdawson** [comment] 2022-07-12 12:56
Still trying to work through the details to see if the RH office is a possibility.

**Comment by ruyadorno** [comment] 2022-07-12 19:56
I'll explore the possibility of hosting it in the Google offices in Dublin too

**Comment by No9** [comment] 2022-07-25 08:06
Apologies for the delay on this - The summer holiday season has really slowed down the required approvals.
Will have a readout during this week.

**Comment by mcollina** [comment] 2022-08-10 09:21
We have a location! We will meet at [Dublin Landings WeWork](https://g.page/WeWork-2-Dublin-Landings?share) on Oct 1-2 2022!
The space will be covered by the OpenJS Foundation while coffee and cleaners will be covered by Red Hat.

**Comment by mcollina** [comment] 2022-08-10 09:21
Who is coming?

**Comment by targos** [comment] 2022-08-10 12:09
I'll be there. Might be able to help depending on the needs.

**Comment by No9** [comment] 2022-08-11 08:18
I'll be there. Let me know how I can help and keep in mind I'm local so I can bring things.

**Comment by ShogunPanda** [comment] 2022-08-16 13:45
I will attend as well! Looking forward to meet you in person folks!

**Comment by ovflowd** [comment] 2022-08-16 14:02
Hey folks 👋 quick question, is there any discount for collaborators? 👀

**Comment by mcollina** [comment] 2022-08-16 14:06
> Hey folks 👋 quick question, is there any discount for collaborators? 👀

At NodeConf.eu?

**Comment by ovflowd** [comment] 2022-08-16 14:06
> At NodeConf.eu?

Yup!

**Comment by mcollina** [comment] 2022-08-16 14:12
I'll see what I can do.

**Comment by Trott** [comment] 2022-08-16 21:21
> Hey folks 👋 quick question, is there any discount for collaborators? 👀

Just to be clear: This is a separate event from NodeConf EU. (It's not even in the same city.) This event is free.

**Comment by ovflowd** [comment] 2022-08-16 21:22
> Just to be clear: This is a separate event from NodeConf EU. (It's not even in the same city.) This event is free.

Oh, I thought it was during NodeConf. So the collaborator summit will be in Dublin, Ireland, right?

**Comment by ovflowd** [comment] 2022-08-16 21:24
Also @mcollina not sure if it is too late, as you already got a space, but my employer, HubSpot could also cede some space (very probably) at no cost. 👀

**Comment by sheplu** [comment] 2022-08-16 21:57
i will be there ! Hope to see a lot of you in Europe this time :)

**Comment by mcollina** [comment] 2022-08-17 09:56
I'll try setting it up, we can look into it a couple of weeks before the event when we know the exact numbers. I've rented a car for some different reason.

**Comment by No9** [comment] 2022-08-17 11:24
Also note the train service in Ireland is now subsidized and has wifi 
Dublin - Waterford is ~€13 prebooked or ~€20 on the platform.
https://www.irishrail.ie/en-ie/Offer/webfares

**Comment by mhdawson** [comment] 2022-08-17 15:57
I will be there and will help. I will only arrive the day before so that might limit the ways I can help.

**Comment by ovflowd** [comment] 2022-08-17 18:25
> Also @mcollina not sure if it is too late, as you already got a space, but my employer, HubSpot could also cede some space (very probably) at no cost. 👀

I apologise if my comment was out of place, just genuinely wanted to offer an alternative. Is there any link for registering for the summit? 👀

**Comment by ruyadorno** [comment] 2022-08-17 18:30
Thanks @No9 that's awesome!

I'm going to be there for the summit and might help running a couple of WG / collaborator sessions.

**Comment by bnb** [comment] 2022-08-17 20:39
two questions:

1. any tips/advice on how to book lodging for both events? IIRC Dublin is pretty far from Lyrath Estates.
2. is there some discounted rate for NodeConf EU for Collab Summit folks?

**Comment by mcollina** [comment] 2022-08-17 20:58
1. you'll need two separate hotels. Book the Lyrath for NodeConf.eu (there should be a link available in the registration process to book the room at a discounted rate). As for Dublin, I think it's free-for-all.
2. there will be a NodeConf.eu discount code for the collab summit attendees. I'll share it with all of you as soon as I have it.

**Comment by Qard** [comment] 2022-08-18 07:33
I _should_ be there. Just working out approvals currently.

**Comment by mcollina** [comment] 2022-08-18 07:46
Here is a discount code: `ColabSummit-Discount2022`.

**Comment by targos** [comment] 2022-08-18 13:13
What do you recommend for the Lyrath? 4 nights from 02 to 05? I think there's no info yet on the conference's timing.

**Comment by mcollina** [comment] 2022-08-18 13:31
In my experience it's better to fly out from Dublin either morning or early afternoon. I almost always experienced delays with late afternoon or evening flights. I'm staying from the 02 to the 06 at the Lyrath.

**Comment by Qard** [comment] 2022-08-18 14:11
Uhhh...anyone else seeing $2700/night prices for 2-6 at Lyrath? 😱

**Comment by targos** [comment] 2022-08-18 14:14
@Qard Use the promo code `node2022` to see the right price.

**Comment by ruyadorno** [comment] 2022-08-18 14:33
yeah, it looks like there's no more regular rooms outside the ones reserved for the event via that promo code.

on a joyful note 🎉 yay! I managed to book one room! actually first time ever I'll be staying in the conf hotel 😂 (and I've been doing these for 10years now)

**Comment by bnb** [comment] 2022-08-19 06:50
> @Qard Use the promo code node2022 to see the right price.

this seems to do nothing to the price for me 👀

**Comment by mcollina** [comment] 2022-08-19 08:57
@bnb I tried it right now and it works. You need to select the dates from 2nd of Oct to the 6th of Oct (or shorter).

**Comment by bnb** [comment] 2022-08-19 18:48
@mcollina ah I think the thing I'm having problem with is that they might be sold out. The only remaining rooms seem to be the most expensive ones that are maybe exempt from that pricing 🙃

**Comment by bnb** [comment] 2022-08-19 18:49
I might be wrong on that though, as the other rooms seem to cost more base.

Here's what I'm seeing: 
![image](https://user-images.githubusercontent.com/502396/185687120-becff2cb-5584-4850-97f9-3fce3d79aa85.png)

**Comment by No9** [comment] 2022-08-19 19:00
@bnb  Yeah I'm seeing a bit of weirdness too 
I pressed the browser back button to the room page I got a line with an option for the reduced rooms.
![image](https://user-images.githubusercontent.com/130940/185688746-1913a820-4bf7-44d2-a905-f747a3761094.png)

**Comment by mcollina** [comment] 2022-08-20 08:43
Our room allotment is _definitely_ not full.

**Comment by No9** [comment] 2022-08-22 07:57
@lmammino watch this issue 😸

**Comment by lmammino** [comment] 2022-08-22 07:58
thanks @No9 !

**Comment by WaleedAshraf** [comment] 2022-08-25 08:07
Hi,

I would like to have a meeting to plan/organize the summit. Anyone who is interested in helping please join. I'll suggest some slots, you can upvote with emoji. Or please suggest another time.

1️⃣ 29th, Monday - 11:00 - 12:00 EST (17:00 - 18:00 CEST)
2️⃣ 30th, Tuesday - 11:00 - 12:00 EST (17:00 - 18:00 CEST)
3️⃣ 31th, Wednesday - 11:00 - 12:00 EST (17:00 - 18:00 CEST)
4️⃣ 1st, Thursday - 11:00 - 12:00 EST (17:00 - 18:00 CEST)
5️⃣ 2nd, Friday - 11:00 - 12:00 EST (17:00 - 18:00 CEST)

**Comment by ovflowd** [comment] 2022-08-25 08:28
> I would like to have a meeting to plan/organize the summit. Anyone who is interested in helping please join. I'll suggest some slots, you can upvote with emoji. Or please suggest another time.

GitHub doesn't support these number emojis...

**Comment by WaleedAshraf** [comment] 2022-08-25 08:33
Eh. :/ We do like this in slack.
Tried to update the smiles. Though it looks weird now. :D

**Comment by Qard** [comment] 2022-08-26 07:22
I'll be at both the collab summit and NodeConf EU. Flying red-eye from NYC the night before the collab summit though, so probably will be barely coherent, but I'll try to survive the day. 😅

**Comment by WaleedAshraf** [comment] 2022-08-26 13:16
Tuesday, 30th it is then. Here's the invite to the meeting.

**Collab Summit Planning**
Tuesday, 30 August · 17:00 – 18:00 (CEST)
Google Meet joining info
Video call link: https://meet.google.com/xxs-rued-apw

**Comment by khaosdoctor** [comment] 2022-08-29 17:43
Will it be possible to join virtually?

**Comment by bnb** [comment] 2022-08-30 15:22
@mcollina is the availability for Lyrath now completely gone? 😅

**Comment by mcollina** [comment] 2022-08-30 16:32
I'll check and get back to you.

**Comment by WaleedAshraf** [comment] 2022-08-30 21:18
> Will it be possible to join virtually?

@khaosdoctor We are working on it. We'll probably have it, but not sure yet. I'll post here if we are able to figure it out.

**Comment by Qard** [comment] 2022-09-01 15:45
Any shared arrangements happening for those of us wanting to get from the collab summit to the conf pre-party on Sunday?

**Comment by WaleedAshraf** [comment] 2022-09-01 19:46
@all
[Register here](https://www.eventbrite.com/e/openjs-foundation-collaborator-summit-dublin-tickets-410575531467). Everyone must register.

@Qard We are looking into getting a bus. Nothing decided yet. You can also take a train. I'll these details on the top.

**Comment by ovflowd** [comment] 2022-09-01 20:05
Question: Are the t-shirt sizes US-based or American-based?

**Comment by MoLow** [comment] 2022-09-08 15:38
@WaleedAshraf I also intend on joining virtually, is it required for me to register?

**Comment by WaleedAshraf** [comment] 2022-09-08 15:45
@MoLow Yes. Both Virtual and In-Person attendees need to register.

**Comment by ovflowd** [comment] 2022-09-10 09:55
Hey folks 👋 I will not be able to attend in-person anymore, can we change my attendance to online?

**Comment by WaleedAshraf** [comment] 2022-09-10 10:56
@ovflowd It's fine. You don't need to change it.
Also note, we are still figuring out virtual attendance. It's not confirmed yet as we need to see what equipment we will get in the WeWork office. I will update here once we have more information. :)

**Comment by ovflowd** [comment] 2022-09-12 16:34
I’m changing my attendance back to in-person as the Foundation is going to expense some of my costs 🙃

**Comment by WaleedAshraf** [comment] 2022-09-18 12:07
I've put up a draft schedule here. Based on feedback from last time, I've tried to fit everything into one track. I had to shorten a few sessions from what they requested.

https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit?usp=sharing

**Comment by mhdawson** [comment] 2022-09-19 22:18
@WaleedAshraf thanks. I think I'll want to attend some of the sessions against which the "next-10 continues is booked" but given that room 2 is not that used we can manage that on the day in terms of how we manage against the other sessions.

**Comment by ErickWendel** [comment] 2022-09-22 17:55
Hey folks 👋 I won't be able to attend in-person anymore :( 

I'll u soon!!

**Comment by ovflowd** [comment] 2022-09-23 09:39
Oh no that sucks. Wishing best of luck :)

**Comment by AdamMomen** [comment] 2022-09-23 18:26
Unfortunately, I have just been notified that my visa got rejected so I can't travel to Ireland to attend the conference.  Nodeconf event managers can change the name of the ticket holder to the new owner.
 
if you're interested in purchasing my ticket reach out to adammuman81@gmail.com.

**Comment by No9** [comment] 2022-09-28 11:31
@mcollina asked me to look up eateries in the near area for the lunch on Saturday.
We will have coffee at the venue but lunch won't be provided.

**5 Min Walk**
Rockets IFSC - Burger Bar
https://www.rockets.ie/menu 
Unit B, N Wall Quay, IFSC District, Dublin 

Elephant and Castle - COFFEE AVAILABLE.
82 N Wall Quay, North Wall, Dublin 1, D01 XR83 
https://themayson.ie/taste/elephantandcastle/



**10 Min Walk**

NutButter 
https://nutbutter.ie/menu/ 
2&3 Gallery Quay, Grand Canal Quay, Dublin 2, D02 R205

Fresh 
Unit 4, Block 1, Grand Canal Square, Dublin Docklands, Dublin 2
General Store that does sandwiches to order
https://freshonline.ie/

**Comment by santigimeno** [comment] 2022-09-29 09:10
> We are looking into getting a bus. Nothing decided yet. You can also take a train. I'll these details on the top.

Planning on how to go to Kilkenny and wondering if there was any decision on the bus thing.

**Comment by mcollina** [comment] 2022-09-29 09:29
We have a bus!
It will leave at 14:00 from `Central Bank Bus Stop N Wall Quay, North Dock, Dublin, D01 F7X3`.

It's a 50 seater.

**Comment by ShogunPanda** [comment] 2022-09-29 09:59
So we can drop all train tickets?

**Comment by ovflowd** [comment] 2022-09-29 10:19
@mcollina is this bus for people going from Collab Summit to the NodeConf or what? (What is this bus supposed to be? For our lunches or something?)

**Comment by mcollina** [comment] 2022-09-29 10:32
It's to go from Dublin to Kilkenny / Lyrath hotel

**Comment by RafaelGSS** [comment] 2022-09-29 11:40
> It's to go from Dublin to Kilkenny / Lyrath hotel

Does it need any kind of reservation? I've bought a train ticket, not quite sure what I should do.

**Comment by ShogunPanda** [comment] 2022-09-29 11:40
> > It's to go from Dublin to Kilkenny / Lyrath hotel
> 
> Does it need any kind of reservation? I've bought a train ticket, not quite sure what I should do.

Same here. What shall we do?

**Comment by targos** [comment] 2022-09-29 12:34
I'll be in Dublin with two colleagues. Can they also take the same bus?

**Comment by mhdawson** [comment] 2022-09-29 16:52
I'd like a spot on the bus :)

**Comment by BethGriggs** [comment] 2022-09-29 16:58
Me too! Perhaps we could create a Google Sheets (or even just a GH issue somewhere) of those planing to take the bus to gauge numbers? Slightly hesitant to cancel my train if there's a chance the bus will be full.

**Comment by Qard** [comment] 2022-09-29 17:46
I'll take a seat on the bus! I haven't got as far as reserving travel between venues yet. I tend to wing it perhaps a bit too much when I travel. 😅

**Comment by Ethan-Arrowood** [comment] 2022-09-29 19:03
I made no travel arrangements yet so I'd love to reserve a seat on the bus if possible.

**Comment by No9** [comment] 2022-09-29 22:45
Currently we have 43 attending the summit in person so there should be enough room for everyone on the bus as it takes 50.
@targos you're colleagues **should** be ok but of course we will prioritize collaborators.

**Comment by sheplu** [comment] 2022-09-30 13:27
I would like a spot on the bus if there is one left :)

**Comment by bnb** [comment] 2022-09-30 20:11
I'd also like a spot on the bus :)

**Comment by santigimeno** [comment] 2022-09-30 21:06
Count me in as well

**Comment by AdamMomen** [comment] 2022-10-01 06:57
@WaleedAshraf where can I find the link to join virtually on eventribe?

**Comment by No9** [comment] 2022-10-01 07:43
@AdamMomen and everyone else, you can see the meetings links in the schedule: https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0

**Comment by WaleedAshraf** [comment] 2022-10-05 22:52
Here are the recordings.
- Main room - Day 1 - Before lunch - [Recording](https://zoom.us/rec/share/lWy6zZ0BoF0RoL_U2W89rhXTSv_vZ2VHisSaNS5jK6BBPqw_RATzw2AAJsIYnCOg.8p4j2lvdYDleN36a?startTime=1664610301000)
- Main room - Day 1 - After lunch - [Recording](https://zoom.us/rec/share/1LRHpZO3VCiHj_Rxo6H9zrNLHEmlz078qVV1RM04D-xS4_0p93stwmYgCJh2DYvX.fqwHsW3fkxyiRAgc?startTime=1664626292000)
- Main room - Day 2 - Before lunch - [Recording](https://zoom.us/rec/share/qMdX1GbYYZSKe-OENy1z50u0GFYx48cRZbu3nisDDbEw0iw5BTwLfJfeJaI0i4pa.nz-AH4JGQNeoK99X?startTime=1664698603000)

I've also added the recording links in the [schedule sheet](https://docs.google.com/spreadsheets/d/1WJpK6ZD43GaI-h-HOuHnG0DmQ8orkxFLbYJ_jUiXX54/edit#gid=0). Sorry, we couldn't record the sessions in the second room. Hopefully next time we'll prepare better.

I'll close this issue as the event has passed. Thanks, everyone for being part of it and for the support.

**Closed by WaleedAshraf** 2022-10-05 22:52 UTC
Labels: Dublin 2022

**Comment by No9** [comment] 2022-10-06 10:20
@tony-go had the big camera during the sessions.

**Comment by tony-go** [comment] 2022-10-10 15:33
Hey 👋 

I put photos [here](https://www.flickr.com/photos/154890703@N06/albums/72177720302771381); note that I was filming more than taking photos ^^

**Comment by AugustinMauroy** [comment] 2022-12-29 20:22
Don't miss to unpin this issue
